### ISSUE TITLE
Word open video with music

### ISSUE THREAD

**Issue by nkapu** [ouspg/urlhandlers#21]
Cut and add music http://www.ee.oulu.fi/~fenris/word-open.mov

**Comment by evilon** [comment]
Word open v0.2 is at https://youtu.be/SsYdSSXYTaY

**Comment by evilon** [comment]
Word open v0.3 is at https://www.youtube.com/watch?v=sjFkTNj8dQU (just fixed the volume to keep this and the Locky video on balance).

**Comment by evilon** [comment]
"Click here" zoom takes away attention from the essential, lets not zoom to that at the end.

**Comment by evilon** [comment]
"Click here" zoom is gone at v0.5 https://youtu.be/5B7QV8iBOYU
