### ISSUE TITLE
Edit twitter video with commentary

### ISSUE THREAD

**Issue by nkapu** [ouspg/urlhandlers#23]

**Comment by evilon** [comment]
Please describe - what do you mean with "commentary"?

**Comment by execgit** [comment]
@nkapu has two videos, one with what's happening on the screen, the other with user commentary. Our idea was to combine these in a picture by picture fashion

**Comment by evilon** [comment]
Ok. I have one video from him. I'll wait a pointer to another and lets have a look.

**Comment by ikisusi** [comment]
There are now two new videos to replace the old one, screen capture with simultaneous face facing camera and audio track. Background noises in the audio track just give it more liveliness, don't worry about them. Some sort of picture in picture and using the commentary as sound is what we were thinking about. Other ideas welcome as well.

**Comment by ikisusi** [comment]
Update, waiting for the HD video to upload. After that @nkapu needs to update the README.md and the repo copy of the video.

**Comment by evilon** [comment]
Yay, the bits flew trough the wormhole to another galaxy and we were able to get info trough the subspace channel that the video has landed to: https://youtu.be/_TkR05uaDWI - @nkapu I guess you're up next?

**Comment by nkapu** [comment]
Thank you @evilon. The twitter video is excellent.
