### ISSUE TITLE
assembly presentation - music to the (locky) infected word video

### ISSUE THREAD

**Issue by ikisusi** [ouspg/urlhandlers#27]
Can we add music to the infected word video? Could it somehow tie together the earlier "open word" video since they are sort of conceptual continuum in same section of the presentation.

**Comment by evilon** [comment]
Could / should we go as far as this: 

https://youtu.be/wtfRzriWh_4?t=12s

e.g. just cut together?

**Comment by evilon** [comment]
If merged - #21 would become reduntant.

**Comment by evilon** [comment]
Locky in Action v0.5-cut  - https://www.youtube.com/watch?v=f_d6W52l7yw

Continues the music from Open word v0.3: https://www.youtube.com/watch?v=sjFkTNj8dQU

**Comment by evilon** [comment]
Ref Locky v0.5 - we should retain the macro clicking.

**Comment by evilon** [comment]
Macro clicking is back at v0.6: https://youtu.be/PKDQhUWEQFM
