### ISSUE TITLE
assembly presentation videos descriptions

### ISSUE THREAD

**Issue by ikisusi** [ouspg/urlhandlers#28]
Should we add a description to each video that has one sentence explanation about the video content:
- [x] xmas: Surfing to a web a page with embedded links of a wide spectrum of URL schemes.
- [x] word-open: `word://` URL auto-launching Microsoft Word with remote content.
- [x] locky: Evil Word document launching a crypto locker if macros are accepted.
- [x] carrousel: New Era for pop-ip advertising with `twitter://` URL as an example advertisement vector.
- [x] panic: When enough is enough,  embedded `applefeedback://` URLs used as an example.

And after the oneliner we could add generic point:

> Featured in URL handlers Assembly 2016 presentation at http://hack.urlhandlers.info/assembly/. More information about the project at https://github.com/ouspg/urlhandlers/

**Comment by evilon** [comment]
Locky done in v0.6, see #27 comments for the link.

**Comment by evilon** [comment]
word-open done in v0.5. See #21 comments for the link

**Comment by evilon** [comment]
xmas done in the frozen version. https://www.youtube.com/watch?v=Z9IG9ZD3PNI

**Comment by evilon** [comment]
carrousel done in the frozen version. https://youtu.be/_TkR05uaDWI

**Comment by evilon** [comment]
panic done in nomusic version. https://youtu.be/I2K4bPCw9SE
